name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted 

    steps:
      - uses: actions/checkout@v2
      - working-directory: src\EphIt
        run: dotnet restore
        name: Restore
      - working-directory: src\EphIt
        name: Build
        run: dotnet build --configuration Release --no-restore
